### ISSUE TITLE
python errors

### ISSUE THREAD

**Issue by noraj** [sleventyeleven/lfimap#3]
```
$ lfimap --target="https://mindreader.web.ctfcompetition.com/?f=/etc/passwd"
Traceback (most recent call last):
  File "lfimap.py", line 384, in <module>
    urlt= autodetect (url, us, pw, prox)
  File "lfimap.py", line 51, in autodetect
    handle = urllib2.urlopen(x)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: NOT FOUND

$ lfimap --target="https://mindreader.web.ctfcompetition.com/"
Traceback (most recent call last):
  File "lfimap.py", line 384, in <module>
    urlt= autodetect (url, us, pw, prox)
  File "lfimap.py", line 15, in autodetect
    params = dict([part.split('=') for part in url[4].split('&')])
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

**Comment by noraj** [comment]
Note: official repo is https://github.com/aepereyra/lfimap
